[package]
name = "rsa-cryptography-rust"
version = "0.1.0"
edition = "2021"
authors = ["Paulo Roberto Albuquerque"]
description = "RSA keys generation, encryption and decryption implemented in rust, for learning purposes only.\nSource code can be viewed in:\nhttps://github.com/paulora2405/rsa-cryptography-rust"

[dependencies]
rand = "0.8.5"
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.15"
clap = { version = "4.0.17", features = ["derive"] }
regex = "1.5.6"
base64 = "0.13.0"
